export const mixMallProduct0s = [
	{
		id: 1,
		name: 'Banana',
		price: 100,
		category: 'Fruits',
		description: 'This [product] is very good',
		sales: 11,
		image: '',
	},
	{
		id: 2,
		name: 'Apple',
		price: 99,
		category: 'Fruits',
		description: 'This [product] is very good',
		sales: 99,
	},

	{
		id: 3,
		name: 'clothes',
		price: 34,
		category: 'Baby',
		description: 'This [product] is very good',
		sales: 10,
		image: '',
	},
	{
		id: 4,
		name: 'milk',
		price: 99,
		category: 'Baby',
		description: 'This [product] is very good',
		sales: 4,
	},

	{
		id: 5,
		name: 'cola',
		price: 4,
		category: 'Baverages',
		description: 'This [product] is very good',
		sales: 88,
		image: '',
	},
	{
		id: 6,
		name: 'fish',
		price: 99,
		category: 'Baverages',
		description: 'This [product] is very good',
		sales: 1,
	},

	{
		id: 7,
		name: 'cola',
		price: 4,
		category: 'Meats',
		description: 'This [product] is very good',
		sales: 88,
		image: '',
	},
	{
		id: 8,
		name: 'kfs',
		price: 49,
		category: 'Meats',
		description: 'This [product] is very good',
		sales: 1,
	},

	{
		id: 9,
		name: 'cola',
		price: 4,
		category: 'Meats',
		description: 'This [product] is very good',
		sales: 28,
		image: '',
	},
	{
		id: 10,
		name: 'cola',
		price: 49,
		category: 'Baverages',
		description: 'This [product] is very good',
		sales: 1,
	},
]
